### ISSUE TITLE
xtb hangs with empty XYZ file input

### ISSUE THREAD

**Issue by ghutchis** [grimme-lab/xtb#371] opened 2020-10-27 13:16 UTC
**Describe the bug**
Run:
```
touch file.xyz
xtb file.xyz
```
xtb will hang, trying to read from the empty file.

**To Reproduce**
Steps to reproduce the behaviour:

See above.

**Expected behaviour**
Normally, I'd expect xtb to quit with an error

**Additional context**
I was running on a batch and evidently one of the files was empty. Not a big deal, but since `xtb` hangs indefinitely, it can use up significant CPU time before the issue is noticed.

**Comment by awvwgk** [comment] 2020-10-27 13:19
Aborts with an error using current master (0ad987d1257e40814cc1b57920c51139c2f420ea):

```
########################################################################
[ERROR] Program stopped due to fatal error
-2- reading geometry input 'empty.xyz' failed
-1- io_reader_readMolecule: Could not read number of atoms, check format!
########################################################################
abnormal termination of xtb
```

**Comment by awvwgk** [comment] 2020-10-28 11:43
Closing since I cannot reproduce this issue. If you have more details on your used environment please clarify.

**Closed by awvwgk** 2020-10-28 11:43 UTC
Labels: unconfirmed
