### ISSUE TITLE
Fix does not work with L-ANCopt

### ISSUE THREAD

**Issue by lsvvt** [grimme-lab/xtb#482] opened 2021-05-18 19:25 UTC
**Describe the bug**
Geometry optimization with $fix does not work with L-ANCopt.

**To Reproduce**
Run calculation with fix and L-ANCopt.

**For example**
Fix C and H in prismane:
Input files:
[C6H6.xyz.txt](https://github.com/grimme-lab/xtb/files/6503749/C6H6.xyz.txt)
[C6H6.xtb.txt](https://github.com/grimme-lab/xtb/files/6503750/C6H6.xtb.txt)

run: xtb --input C6H6.xtb C6H6.xyz -P 1 --gfn 2 --opt --verbose > C6H6.log

logs:
[C6H6.log](https://github.com/grimme-lab/xtb/files/6503773/C6H6.log)
[xtbopt.log](https://github.com/grimme-lab/xtb/files/6503775/xtbopt.log)

As you can see from the file xtbopt.log, something strange is happening with the molecule.

**Comment by awvwgk** [comment] 2021-05-18 19:33
Duplicate of #410

**Comment by awvwgk** [comment] 2021-05-18 19:33
Might be fixed with https://github.com/grimme-lab/xtb/pull/433 already.

**Closed** 2021-05-18 20:02 UTC
Labels: duplicate
