### ISSUE TITLE
Hessian calculation seg. faults with 6.4.0, not with 6.3.3

### ISSUE THREAD

**Issue by leforesb** [grimme-lab/xtb#487] opened 2021-05-31 15:59 UTC
**Describe the bug**
Numerical hessian calculation(s?) crashes with segmentation fault in xTB version 6.4.0, but runs smoothly with version 6.3.3

**To Reproduce**

1. happens with this example geometry:
[xtbopt.txt](https://github.com/grimme-lab/xtb/files/6571272/xtbopt.txt)

2. start `xtb` with the flag `--hess` and all other parameters as default (see output files).

**Expected behaviour**
Normal termination of the calculation with xTB 6.4.0 

**Additional context**
Output files attached:
[output_633.txt](https://github.com/grimme-lab/xtb/files/6571275/output_633.txt)
[output_640.txt](https://github.com/grimme-lab/xtb/files/6571277/output_640.txt)

Both calculations were run concomitently on the same machine, node and identical environment.
More unexpectedly, successful hessian calculations could still be performed with xTB 6.4.0 on different structures, with both larger or smaller numbers of atoms, still on the same machine, node and identical environment.

**Comment by awvwgk** [comment] 2021-05-31 17:06
Duplicate of https://github.com/grimme-lab/xtb/issues/458

**Comment by awvwgk** [comment] 2021-05-31 17:07
Should be fixed with https://github.com/grimme-lab/xtb/pull/465 which will be part of version 6.4.1

**Closed** 2021-06-01 14:21 UTC
Labels: duplicate
