### ISSUE TITLE
Probably broken release

### ISSUE THREAD

**Issue by SomeAnonimCoder** [grimme-lab/xtb#360] opened 2020-10-02 19:53 UTC
**Description**
Release file (https://github.com/grimme-lab/xtb/releases/download/v6.3.3/xtb-200917.tar.xz) doesn't work for any xyz file.

**To Reproduce**
Steps to reproduce the behaviour:
1. happens with input:
caffeine example from docs, and any other too. Caffeine example:
```
24
C          1.07317        0.04885       -0.07573
N          2.51365        0.01256       -0.07580
C          3.35199        1.09592       -0.07533
N          4.61898        0.73028       -0.07549
C          4.57907       -0.63144       -0.07531
C          3.30131       -1.10256       -0.07524
C          2.98068       -2.48687       -0.07377
O          1.82530       -2.90038       -0.07577
N          4.11440       -3.30433       -0.06936
C          5.45174       -2.85618       -0.07235
O          6.38934       -3.65965       -0.07232
N          5.66240       -1.47682       -0.07487
C          7.00947       -0.93648       -0.07524
C          3.92063       -4.74093       -0.06158
H          0.73398        1.08786       -0.07503
H          0.71239       -0.45698        0.82335
H          0.71240       -0.45580       -0.97549
H          2.99301        2.11762       -0.07478
H          7.76531       -1.72634       -0.07591
H          7.14864       -0.32182        0.81969
H          7.14802       -0.32076       -0.96953
H          2.86501       -5.02316       -0.05833
H          4.40233       -5.15920        0.82837
H          4.40017       -5.16929       -0.94780

```

2. start `xtb` with `xtb file.xyz --opt`
```           -------------------------------------------------
          |                Calculation Setup                |
           -------------------------------------------------

          program call               : ./xtb-6.3.3/bin/xtb caffeine.xyz
          coordinate file            : caffeine.xyz
          omp threads                :                    24
          number of atoms            :                    24
          number of electrons        :                    74
          charge                     :                     0
          spin                       :                   0.0
          first test random number   :      0.19289954583927

   ID    Z sym.   atoms
    1    6 C      1, 3, 5-7, 10, 13, 14
    2    7 N      2, 4, 9, 12
    3    8 O      8, 11
    4    1 H      15-24

           -------------------------------------------------
          |                 G F N 2 - x T B                 |
           -------------------------------------------------

        Reference                      10.1021/acs.jctc.8b01176
      * Hamiltonian:
        H0-scaling (s, p, d)           1.850000    2.230000    2.230000
        zeta-weighting                 0.500000
      * Dispersion:
        s8                             2.700000
        a1                             0.520000
        a2                             5.000000
        s9                             5.000000
      * Repulsion:
        kExp                           1.500000    1.000000
        rExp                           1.000000
      * Coulomb:
        alpha                          2.000000
        third order                    shell-resolved
        anisotropic                    true
        a3                             3.000000
        a5                             4.000000
        cn-shift                       1.200000
        cn-exp                         4.000000
        max-rad                        5.000000

q/qsh data taken from xtbrestart
CAMM data taken from xtbrestart

          ...................................................
          :                      SETUP                      :
          :.................................................:
          :  # basis functions                  66          :
          :  # atomic orbitals                  66          :
          :  # shells                           38          :
          :  # electrons                        74          :
          :  max. iterations                   250          :
          :  Hamiltonian                  GFN2-xTB          :
          :  restarted?                       true          :
          :  GBSA solvation                  false          :
          :  PC potential                    false          :
          :  electronic temp.          300.0000000     K    :
          :  accuracy                    1.0000000          :
          :  -> integral cutoff          0.2500000E+02      :
          :  -> integral neglect         0.1000000E-07      :
          :  -> SCF convergence          0.1000000E-05 Eh   :
          :  -> wf. convergence          0.1000000E-03 e    :
          :  Broyden damping             0.4000000          :
          ...................................................

 iter      E             dE          RMSdq      gap      omega  full diag
########################################################################
[ERROR] Program stopped due to fatal error
-6- Single point calculation terminated
-5- xtb_calculator_singlepoint: Electronic structure method terminated
-4- scf: Self consistent charge iterator terminated
-3- scc_core: Diagonalization of Hamiltonian failed
-2- mctc_lapack_sygvd: Failed to solve eigenvalue problem
-1- mctc_lapack_potrf: Factorisation of matrix failed
########################################################################
abnormal termination of xtb
```
3. run `xtb` with your options and the `--verbose` flag
```           -------------------------------------------------
          |                Calculation Setup                |
           -------------------------------------------------

          program call               : ./xtb-6.3.3/bin/xtb caffeine.xyz --verbose
          coordinate file            : caffeine.xyz
          xtbhome directory          : /home/someanonimcoder
          path for xtb               : /home/someanonimcoder
          xcontrol input file        : caffeine.xyz
          omp threads                :                    24
          number of atoms            :                    24
          number of electrons        :                    74
          charge                     :                     0
          spin                       :                   0.0
          first test random number   :      0.27980946227154
          a pointer address          :            0x3E8F4330
          random memory content      :      3FD1E865F26453A9

$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
 CONSTRAINTS & SCANS: DEBUG SECTION
$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
   ID    Z sym.   atoms
    1    6 C      1, 3, 5-7, 10, 13, 14
    2    7 N      2, 4, 9, 12
    3    8 O      8, 11
    4    1 H      15-24
$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$

           -------------------------------------------------
          |                 G F N 2 - x T B                 |
           -------------------------------------------------

        Reference                      10.1021/acs.jctc.8b01176
      * Hamiltonian:
        H0-scaling (s, p, d)           1.850000    2.230000    2.230000
        zeta-weighting                 0.500000
      * Dispersion:
        s8                             2.700000
        a1                             0.520000
        a2                             5.000000
        s9                             5.000000
      * Repulsion:
        kExp                           1.500000    1.000000
        rExp                           1.000000
      * Coulomb:
        alpha                          2.000000
        third order                    shell-resolved
        anisotropic                    true
        a3                             3.000000
        a5                             4.000000
        cn-shift                       1.200000
        cn-exp                         4.000000
        max-rad                        5.000000

q/qsh data taken from xtbrestart
CAMM data taken from xtbrestart

          ...................................................
          :                      SETUP                      :
          :.................................................:
          :  # basis functions                  66          :
          :  # atomic orbitals                  66          :
          :  # shells                           38          :
          :  # electrons                        74          :
          :  max. iterations                   250          :
          :  Hamiltonian                  GFN2-xTB          :
          :  restarted?                       true          :
          :  GBSA solvation                  false          :
          :  PC potential                    false          :
          :  electronic temp.          300.0000000     K    :
          :  accuracy                    1.0000000          :
          :  -> integral cutoff          0.2500000E+02      :
          :  -> integral neglect         0.1000000E-07      :
          :  -> SCF convergence          0.1000000E-05 Eh   :
          :  -> wf. convergence          0.1000000E-03 e    :
          :  Broyden damping             0.4000000          :
          ...................................................

 iter      E             dE          RMSdq      gap      omega  full diag
########################################################################
[ERROR] Program stopped due to fatal error
-6- Single point calculation terminated
-5- xtb_calculator_singlepoint: Electronic structure method terminated
-4- scf: Self consistent charge iterator terminated
-3- scc_core: Diagonalization of Hamiltonian failed
-2- mctc_lapack_sygvd: Failed to solve eigenvalue problem
-1- mctc_lapack_potrf: Factorisation of matrix failed
########################################################################
abnormal termination of xtb
```
4. output showing the error
```[ERROR] Program stopped due to fatal error
-6- Single point calculation terminated
-5- xtb_calculator_singlepoint: Electronic structure method terminated
-4- scf: Self consistent charge iterator terminated
-3- scc_core: Diagonalization of Hamiltonian failed
-2- mctc_lapack_sygvd: Failed to solve eigenvalue problem
-1- mctc_lapack_potrf: Factorisation of matrix failed
########################################################################
abnormal termination of xtb```

**Expected behaviour**
Correct optimization
**Additional context**
This happened on two different machines, and on both of them manually compilled from source with just `cmake & make` xtb works correctly.

**Comment by awvwgk** [comment] 2020-10-03 06:07
That is strange, I setup the very same binary on our cluster as default version and we didn't observe any problems over the past week with it.

Could you verify that the checksum of the package and the binary matches the one I'm using:
```
sha256sum xtb-6.3.3/bin/xtb xtb-200917.tar.xz
3b3e73a34b89b8560d22816a349c648d98975d0103ced85e087251e20d8a5796  xtb-6.3.3/bin/xtb
2e29899252c2a6144a546c6c21ecb425f56111e739a092078b0c14cbd64112bf  xtb-200917.tar.xz
```

I just checked the package I uploaded on the cluster again and on my laptop but could not find any failure.

**Comment by awvwgk** [comment] 2020-10-08 16:40
@SomeAnonimCoder Is this still an issue?

**Comment by awvwgk** [comment] 2020-10-28 11:44
Closing this since I cannot reproduce the issue. If you have more details on your used environment please clarify.

**Closed by awvwgk** 2020-10-28 11:44 UTC
Labels: unconfirmed
