### ISSUE TITLE
Compiling problem

### ISSUE THREAD

**Issue by LePingKYXK** [grimme-lab/xtb#459] opened 2021-03-22 03:02 UTC
Hi, 
I got a problem when compiling the `xTB 6.4.0` using the `Intel compiler (v2018.1.163)`. In addition, `meson (v0.57.1)`, and `ninja (v1.10.2)` are the latest versions. 

The details are shown below. It would be greatly appreciated if anyone provides some suggestions.

```bash
[root@master xtb-6.4.0]# 
[root@master xtb-6.4.0]# source /public1/apps/intel/mkl/bin/mklvars.sh intel64
[root@master xtb-6.4.0]# export PATH="/public1/apps/intel/bin/:$PATH"
[root@master xtb-6.4.0]# export FC=ifort CC=icc
[root@master xtb-6.4.0]# meson setup build --buildtype release --optimization 2
WARNING: Recommend using either -Dbuildtype or -Doptimization + -Ddebug. Using both is redundant since they override each other. See: https://mesonbuild.com/Builtin-options.html#build-type-options
The Meson build system
Version: 0.57.1
Source dir: /public2/wanghuan/Backup/xtb-6.4.0
Build dir: /public2/wanghuan/Backup/xtb-6.4.0/build
Build type: native build
Project name: xtb
Project version: 6.4.0
Fortran compiler for the host machine: ifort (intel 18.0.1 "ifort (IFORT) 18.0.1 20171018")
Fortran linker for the host machine: ifort ld.bfd 2.25.1-31
C compiler for the host machine: icc (intel 18.0.1 "icc (ICC) 18.0.1 20171018")
C linker for the host machine: icc ld.bfd 2.25.1-31
Host machine cpu family: x86_64
Host machine cpu: x86_64
Program git found: YES (/usr/bin/git)
Program date found: YES (/usr/bin/date)
Program whoami found: YES (/usr/bin/whoami)
Program hostname found: YES (/usr/bin/hostname)
Configuring xtb_version.fh using configuration
Library mkl_rt found: YES
Library mkl_intel_lp64 found: YES
Library mkl_intel_thread found: YES
Library mkl_core found: YES
Run-time dependency OpenMP found: YES 5.0-revision1
Run-time dependency threads found: YES
Program asciidoctor found: YES (/usr/local/bin/asciidoctor)
Configuring xtb.1 with command
Configuring xcontrol.7 with command
Configuring config_env.bash using configuration
Configuring config_env.csh using configuration
Configuring xtb.pc using configuration
Configuring xtb.tcl using configuration
TESTSUITE/meson.build:53: DEPRECATION: ":" is not allowed in test name "Argparser: print version", it has been replaced with "_"
TESTSUITE/meson.build:54: DEPRECATION: ":" is not allowed in test name "Argparser: print help", it has been replaced with "_"
TESTSUITE/meson.build:55: DEPRECATION: ":" is not allowed in test name "Argparser: print license", it has been replaced with "_"
TESTSUITE/meson.build:56: DEPRECATION: ":" is not allowed in test name "Argparser: no arguments", it has been replaced with "_"
TESTSUITE/meson.build:78: DEPRECATION: ":" is not allowed in test name "Molecule: axis", it has been replaced with "_"
TESTSUITE/meson.build:79: DEPRECATION: ":" is not allowed in test name "Molecule: MIC", it has been replaced with "_"
TESTSUITE/meson.build:80: DEPRECATION: ":" is not allowed in test name "Lattice points: PBC-3D", it has been replaced with "_"
TESTSUITE/meson.build:88: DEPRECATION: ":" is not allowed in test name "IO: atom list", it has been replaced with "_"
TESTSUITE/meson.build:107: DEPRECATION: ":" is not allowed in test name "PBC tools: convert", it has been replaced with "_"
TESTSUITE/meson.build:108: DEPRECATION: ":" is not allowed in test name "PBC tools: cutoff", it has been replaced with "_"
TESTSUITE/meson.build:110: DEPRECATION: ":" is not allowed in test name "Symmetry: Water", it has been replaced with "_"
TESTSUITE/meson.build:111: DEPRECATION: ":" is not allowed in test name "Symmetry: Li8", it has been replaced with "_"
TESTSUITE/meson.build:112: DEPRECATION: ":" is not allowed in test name "Symmetry: PCl3", it has been replaced with "_"
TESTSUITE/meson.build:113: DEPRECATION: ":" is not allowed in test name "Symmetry: large", it has been replaced with "_"
TESTSUITE/meson.build:115: DEPRECATION: ":" is not allowed in test name "Thermo: axis", it has been replaced with "_"
TESTSUITE/meson.build:116: DEPRECATION: ":" is not allowed in test name "Thermo: calculation", it has been replaced with "_"
TESTSUITE/meson.build:117: DEPRECATION: ":" is not allowed in test name "Thermo: print", it has been replaced with "_"
TESTSUITE/meson.build:119: DEPRECATION: ":" is not allowed in test name "Repulsion: 0D", it has been replaced with "_"
TESTSUITE/meson.build:120: DEPRECATION: ":" is not allowed in test name "Repulsion: 3D", it has been replaced with "_"
TESTSUITE/meson.build:122: DEPRECATION: ":" is not allowed in test name "Coulomb: point (0D)", it has been replaced with "_"
TESTSUITE/meson.build:123: DEPRECATION: ":" is not allowed in test name "Coulomb: point (3D)", it has been replaced with "_"
TESTSUITE/meson.build:124: DEPRECATION: ":" is not allowed in test name "Coulomb: GFN1 (0D)", it has been replaced with "_"
TESTSUITE/meson.build:125: DEPRECATION: ":" is not allowed in test name "Coulomb: GFN1 (3D)", it has been replaced with "_"
TESTSUITE/meson.build:126: DEPRECATION: ":" is not allowed in test name "Coulomb: GFN2 (0D)", it has been replaced with "_"
TESTSUITE/meson.build:127: DEPRECATION: ":" is not allowed in test name "Coulomb: GFN2 (3D)", it has been replaced with "_"
TESTSUITE/meson.build:128: DEPRECATION: ":" is not allowed in test name "Coulomb: Gauss. (0D)", it has been replaced with "_"
TESTSUITE/meson.build:129: DEPRECATION: ":" is not allowed in test name "Coulomb: Gauss. (3D)", it has been replaced with "_"
TESTSUITE/meson.build:131: DEPRECATION: ":" is not allowed in test name "EEQ model: water", it has been replaced with "_"
TESTSUITE/meson.build:132: DEPRECATION: ":" is not allowed in test name "EEQ model: 3D Ewald", it has been replaced with "_"
TESTSUITE/meson.build:133: DEPRECATION: ":" is not allowed in test name "EEQ model: GBSA", it has been replaced with "_"
TESTSUITE/meson.build:134: DEPRECATION: ":" is not allowed in test name "EEQ model: GBSA (salt)", it has been replaced with "_"
TESTSUITE/meson.build:135: DEPRECATION: ":" is not allowed in test name "EEQ model: GBSA (H-bond)", it has been replaced with "_"
TESTSUITE/meson.build:137: DEPRECATION: ":" is not allowed in test name "CN: latticepoints", it has been replaced with "_"
TESTSUITE/meson.build:138: DEPRECATION: ":" is not allowed in test name "CN: neighbourlist", it has been replaced with "_"
TESTSUITE/meson.build:139: DEPRECATION: ":" is not allowed in test name "DFT-D3: latticepoints", it has been replaced with "_"
TESTSUITE/meson.build:140: DEPRECATION: ":" is not allowed in test name "DFT-D3: neighbourlist", it has been replaced with "_"
TESTSUITE/meson.build:141: DEPRECATION: ":" is not allowed in test name "DFT-D3: threebody (LP)", it has been replaced with "_"
TESTSUITE/meson.build:142: DEPRECATION: ":" is not allowed in test name "DFT-D3: threebody (NL)", it has been replaced with "_"
TESTSUITE/meson.build:143: DEPRECATION: ":" is not allowed in test name "DFT-D4: latticepoints", it has been replaced with "_"
TESTSUITE/meson.build:144: DEPRECATION: ":" is not allowed in test name "DFT-D4: neighbourlist", it has been replaced with "_"
TESTSUITE/meson.build:145: DEPRECATION: ":" is not allowed in test name "DFT-D4: threebody (LP)", it has been replaced with "_"
TESTSUITE/meson.build:146: DEPRECATION: ":" is not allowed in test name "DFT-D4: threebody (NL)", it has been replaced with "_"
TESTSUITE/meson.build:148: DEPRECATION: ":" is not allowed in test name "GFN2-xTB: Basic", it has been replaced with "_"
TESTSUITE/meson.build:149: DEPRECATION: ":" is not allowed in test name "GFN2-xTB: Solvation", it has been replaced with "_"
TESTSUITE/meson.build:150: DEPRECATION: ":" is not allowed in test name "GFN2-xTB: SCC", it has been replaced with "_"
TESTSUITE/meson.build:151: DEPRECATION: ":" is not allowed in test name "GFN2-xTB: API", it has been replaced with "_"
TESTSUITE/meson.build:152: DEPRECATION: ":" is not allowed in test name "GFN2-xTB: API (GBSA)", it has been replaced with "_"
TESTSUITE/meson.build:153: DEPRECATION: ":" is not allowed in test name "GFN2-xTB: API (GBSA+salt)", it has been replaced with "_"
TESTSUITE/meson.build:154: DEPRECATION: ":" is not allowed in test name "GFN2-xTB: d-Metal", it has been replaced with "_"
TESTSUITE/meson.build:155: DEPRECATION: ":" is not allowed in test name "GFN2-xTB: Freq", it has been replaced with "_"
TESTSUITE/meson.build:158: DEPRECATION: ":" is not allowed in test name "GFN2-xTB: C", it has been replaced with "_"
TESTSUITE/meson.build:169: DEPRECATION: ":" is not allowed in test name "GFN1-xTB: Basic", it has been replaced with "_"
TESTSUITE/meson.build:170: DEPRECATION: ":" is not allowed in test name "GFN1-xTB: Solvation", it has been replaced with "_"
TESTSUITE/meson.build:171: DEPRECATION: ":" is not allowed in test name "GFN1-xTB: SCC", it has been replaced with "_"
TESTSUITE/meson.build:172: DEPRECATION: ":" is not allowed in test name "GFN1-xTB: API", it has been replaced with "_"
TESTSUITE/meson.build:173: DEPRECATION: ":" is not allowed in test name "GFN1-xTB: XB", it has been replaced with "_"
TESTSUITE/meson.build:174: DEPRECATION: ":" is not allowed in test name "GFN1-xTB: PBC", it has been replaced with "_"
TESTSUITE/meson.build:175: DEPRECATION: ":" is not allowed in test name "GFN1-xTB: API (GBSA)", it has been replaced with "_"
TESTSUITE/meson.build:176: DEPRECATION: ":" is not allowed in test name "GFN1-xTB: API (PCEM)", it has been replaced with "_"
TESTSUITE/meson.build:177: DEPRECATION: ":" is not allowed in test name "GFN1-xTB: IPEA", it has been replaced with "_"
TESTSUITE/meson.build:178: DEPRECATION: ":" is not allowed in test name "GFN1-xTB: Freq", it has been replaced with "_"
TESTSUITE/meson.build:180: DEPRECATION: ":" is not allowed in test name "GFN0-xTB: Basic", it has been replaced with "_"
TESTSUITE/meson.build:181: DEPRECATION: ":" is not allowed in test name "GFN0-xTB: Solvation", it has been replaced with "_"
TESTSUITE/meson.build:182: DEPRECATION: ":" is not allowed in test name "GFN0-xTB: SP", it has been replaced with "_"
TESTSUITE/meson.build:183: DEPRECATION: ":" is not allowed in test name "GFN0-xTB: API", it has been replaced with "_"
TESTSUITE/meson.build:184: DEPRECATION: ":" is not allowed in test name "GFN0-xTB: SRB", it has been replaced with "_"
TESTSUITE/meson.build:185: DEPRECATION: ":" is not allowed in test name "GFN0-xTB: SP  (PBC)", it has been replaced with "_"
TESTSUITE/meson.build:186: DEPRECATION: ":" is not allowed in test name "GFN0-xTB: API (PBC)", it has been replaced with "_"
TESTSUITE/meson.build:187: DEPRECATION: ":" is not allowed in test name "GFN0-xTB: SRB (PBC)", it has been replaced with "_"
TESTSUITE/meson.build:189: DEPRECATION: ":" is not allowed in test name "GFN-FF: Basic", it has been replaced with "_"
TESTSUITE/meson.build:190: DEPRECATION: ":" is not allowed in test name "GFN-FF: Solvation", it has been replaced with "_"
TESTSUITE/meson.build:191: DEPRECATION: ":" is not allowed in test name "GFN-FF: SP", it has been replaced with "_"
TESTSUITE/meson.build:192: DEPRECATION: ":" is not allowed in test name "GFN-FF: HB", it has been replaced with "_"
TESTSUITE/meson.build:193: DEPRECATION: ":" is not allowed in test name "GFN-FF: GBSA", it has been replaced with "_"
TESTSUITE/meson.build:194: DEPRECATION: ":" is not allowed in test name "GFN-FF: Scale-up", it has been replaced with "_"
TESTSUITE/meson.build:195: DEPRECATION: ":" is not allowed in test name "GFN-FF: PDB", it has been replaced with "_"
TESTSUITE/meson.build:196: DEPRECATION: ":" is not allowed in test name "GFN-FF: SDF", it has been replaced with "_"
Build targets in project: 6

Option buildtype is: release [default: debugoptimized]
Found ninja-1.10.0.git.kitware.jobserver-1 at /public1/apps/miniconda3/envs/xtb/bin/ninja
[root@master xtb-6.4.0]# 
```

**Comment by LePingKYXK** [comment] 2021-03-22 04:51
I tried to downgrade the meson to version 0.52. It seems OK.

However, I got another problem when running `ninja -C build test`

[519/552] Linking target TESTSUITE/xtb_c_test.
FAILED: TESTSUITE/xtb_c_test 
icc  -o TESTSUITE/xtb_c_test 'TESTSUITE/477912c@@xtb_c_test@exe/c_api_example.c.o' -Wl,--as-needed -Wl,--no-undefined -static -Wl,--start-group lib_xtb.a -lmkl_intel_lp64 -lmkl_intel_thread -lmkl_core -qopenmp -pthread -lmkl_intel_lp64 -lmkl_intel_thread -lmkl_core -qopenmp '-Wl,-rpath,$ORIGIN/..' -Wl,-rpath-link,/public2/wanghuan/Backup/xtb-6.4.0/build/ -lifcore -limf -Wl,--end-group
/opt/rh/devtoolset-9/root/usr/libexec/gcc/x86_64-redhat-linux/9/ld: cannot find -lm
/opt/rh/devtoolset-9/root/usr/libexec/gcc/x86_64-redhat-linux/9/ld: cannot find -lpthread
/opt/rh/devtoolset-9/root/usr/libexec/gcc/x86_64-redhat-linux/9/ld: cannot find -lc
/opt/rh/devtoolset-9/root/usr/libexec/gcc/x86_64-redhat-linux/9/ld: cannot find -ldl
/opt/rh/devtoolset-9/root/usr/libexec/gcc/x86_64-redhat-linux/9/ld: cannot find -lc

**Comment by awvwgk** [comment] 2021-03-22 07:51
I highly recommend to not build `xtb` as root, there is no need for this. The problem regarding meson 0.57.1 is tracked here https://github.com/grimme-lab/xtb/issues/442 and already reported and fixed in upstream meson.

As for the linking issue, make sure your system can actually link statically, if this is not possible, use `-Dla_backend=mkl` instead.

Duplicate of #442

**Closed by awvwgk** 2021-03-22 07:51 UTC
Labels: unconfirmed

**Comment by LePingKYXK** [comment] 2021-03-24 02:59
Thank you for your response. But I am not clear about what is "system can actually link statically", and which command should I add the `-Dla_backend=mkl`?

**Comment by awvwgk** [comment] 2021-03-24 07:42
This looks goods. Expected fail means exactly that, the test is expected to fail because it tests an error.
