### ISSUE TITLE
Reading of VASP input formats

### ISSUE THREAD

**Issue by arosen93** [grimme-lab/xtb#165] opened 2020-04-03 20:52 UTC
**Describe the bug**
One would expect to be able to read in a POSCAR or CONTCAR with that as the filename, but it does not work.

**To Reproduce**
`xtb --gfn 0 POSCAR` fails, although `xtb --gfn 0 poscar.vasp` works. 

**Expected behaviour**
Read in POSCAR

**Additional context**
It took me a while to find out that a suffix was needed to read in the geometry of a POSCAR. VASP itself reads in POSCARs and CONTCARs with the filename `POSCAR` and `CONTCAR`, which is the standard naming convention and should probably be adopted here too to prevent confusion.

**Comment by awvwgk** [comment] 2020-04-04 13:21
Works fine with the current master (9d81278) and release v6.2.3, please check your files in info mode with the current master and report the output from:

```
xtb info POSCAR CONTCAR
```

**Comment by awvwgk** [comment] 2020-04-04 13:25
A fix for this was implemented with 57a2aea in #80.

**Comment by awvwgk** [comment] 2020-04-08 20:57
Closing this, since it cannot be reproduced with the current stable release.

**Closed by awvwgk** 2020-04-08 20:57 UTC
Labels: invalid
