### ISSUE TITLE
Crashes with tmQM structures

### ISSUE THREAD

**Issue by andersx** [grimme-lab/xtb#369] opened 2020-10-19 13:06 UTC
**Describe the bug**

Hi xtb! I'm having some hard crashes when running single-point on structures from the tmQM dataset. It seems to affect about 1 in 20 of my runs. One example below. Any idea what could cause this?

Thanks!

**To Reproduce**
Steps to reproduce the behaviour:

1. happens with input (include input files)

Using the structure AJUQAZ.xyz from the recent tmQM dataset.

```
106

W         2.78980511071738    9.48947716969557    9.90785630334890
C         3.43013870320690    7.77842472562643   10.58440196156309
O         3.80879627448493    6.71741134190376   10.88007523993774
C         2.74116445296270   10.03946448896181   11.73223185423908
O         2.64252420118320   10.43250293038193   12.89581974520666
C         1.62925518526322   10.93349835101832    8.40907132443457
C         0.66066557926611   10.15536983102813    9.10319851740903
C         0.87680938449061    8.78467267073635    8.77391252145411
C         1.96169671590606    8.72120728417871    7.84726504174126
C         2.41528705959570   10.04138681773778    7.61577657932740
C         1.64000014440872   12.43056755203261    8.28170012215702
H         0.95851863814805   12.74984966777165    7.48640274506102
H         2.63640300980008   12.79573891428840    8.03578028063988
H         1.32842757199347   12.91004863505353    9.20660877055503
C        -0.55866207656962   10.68327184177935    9.80553878758554
H        -1.45703954681402   10.39507825891932    9.25277932054174
H        -0.53350576521140   11.76888235257663    9.85795704807304
H        -0.65033485635107   10.29414511986876   10.81910632501468
C        -0.05387562771078    7.64465390760756    9.07527016549821
H         0.48092689099228    6.77462288831557    9.45917028300661
H        -0.57740971468341    7.33613699011959    8.16541775994834
H        -0.80002739912888    7.94094567278287    9.80973106443055
C         2.38605602540645    7.48228255902143    7.11097611814221
H         1.75179224971407    7.32064113275463    6.23343608942040
H         2.30317692550909    6.60371721922727    7.75082712752702
H         3.41919533036653    7.55688327766277    6.77184843259271
C         3.36528221885401   10.46146404733987    6.53173793948920
H         2.80683014051013   10.68741572462522    5.61832803321374
H         4.07985947448171    9.67287143349578    6.30161297636139
H         3.92518297497406   11.35318073795372    6.81117389673883
Si        5.14004014849758    9.94496276484240    9.59909104442499
C         6.76437038975260   10.59313010116769   10.46351242591536
Si        6.36489849104950   10.97946846504171   12.32888729097746
Si        8.12738580124288    9.22972762535418   10.32136506711834
Si        7.23169066145156   12.19749290376697    9.49344434703007
C         5.21205384097600   12.49208961737932   12.42631846252534
H         4.27963025267778   12.28522447497495   11.91195419939608
H         5.64991079661321   13.38395471377473   11.99165586559654
H         4.96572513929026   12.71919402035839   13.45752680013107
C         7.93028326729019   11.38580226178297   13.36165520304645
H         8.55880428951436   10.51041083606178   13.48650156927035
H         7.63802090355634   11.71594583578518   14.35422999951822
H         8.53645508922098   12.16962332536671   12.92538140254228
C         5.56139808717004    9.52050793515732   13.25249005227644
H         4.95256711155371    8.90830197536986   12.59588892370802
H         4.90649347301598    9.89576681949071   14.03106025098136
H         6.29260287049895    8.88009794850065   13.73222891695863
C         7.84887585836003    7.79182889078944   11.53959301872839
H         8.46807262382501    6.93883153633944   11.27758802480433
H         6.81594221464014    7.46291491015930   11.52572003033356
H         8.09395898162191    8.07024686498490   12.55729638234114
C         9.88444268877421    9.92911264083231   10.63684618772425
H        10.19563181259284   10.61310605767253    9.85505855860173
H        10.61378609882227    9.12506852401194   10.67675403973216
H         9.93604903131097   10.46242815653773   11.57788652588733
C         8.21801891382881    8.36081163527262    8.61639578732836
H         8.26964385892382    9.05650065534661    7.78860651051293
H         7.34869460068584    7.73007277780135    8.46597646173024
H         9.09649416732124    7.72359103326791    8.56097929244148
C         8.11100380681529   11.87101659206997    7.82095920525654
H         7.50346471966043   11.24549472440501    7.17656479822953
H         9.07167895021327   11.38490306666790    7.94500635183990
H         8.28337305380348   12.80545356657873    7.29379414917411
C         8.39425344901696   13.39496309838606   10.42587615538011
H         8.66620588876101   14.23360212711190    9.79121219660685
H         9.31228501032974   12.90674447085482   10.73095509247576
H         7.92029575466023   13.79655373239682   11.31331268330731
C         5.66193271933383   13.17368446244946    9.00067910904885
H         5.30688060813481   12.85149589463464    8.02680122285465
H         5.85516434289878   14.24044676861273    8.93594647865805
H         4.85248347224645   13.02684598721273    9.70471452433638
B         1.46036604638846   10.26281502457361   13.83996736205469
C         0.63416213225445   11.67687386085682   13.83869812628898
C         0.61846317673725   12.53738209650472   12.74611512759427
C        -0.08021785978545   13.74075070178139   12.74458285893420
C        -0.79263341616877   14.13024062441132   13.86852079012740
C        -0.79342683365533   13.30055431570210   14.98208767904898
C        -0.08953924484181   12.10377243802308   14.94758985473896
F         1.28565169726513   12.23662052823090   11.62269284208061
F        -0.06867090907720   14.52591214395421   11.65394105062168
F        -1.46848294771754   15.28917719341122   13.88124827938463
F        -1.47298663073338   13.66288925106658   16.08165013834164
F        -0.13590628750875   11.33932110575365   16.05258731084693
C         0.57002436340246    9.00323912921421   13.32135338052865
C        -0.79627433265421    9.01244955693954   13.08599915922964
C        -1.48570275995120    7.90604355380082   12.59995452124208
C        -0.79484225146331    6.73655973555653   12.31530788565184
C         0.57632483178473    6.68830413100506   12.52926320738928
C         1.23328108224009    7.81273167077218   13.01561111559993
F        -1.52859011551590   10.11482934894482   13.34563535150069
F        -2.81564754902205    7.96267643539982   12.40616732693077
F        -1.45007697871507    5.66161169381306   11.84999491104095
F         1.23954584222210    5.55327489626475   12.28129364562462
F         2.53653782737169    7.69893053275153   13.30077685555075
C         2.12318751275836   10.01776700150896   15.31125858737496
C         1.90507311993190    8.91954996991615   16.13622534673207
C         2.55950572172821    8.74667128620685   17.35105000580556
C         3.47076458346774    9.69743267415000   17.79011300433494
C         3.69263485264302   10.82408037336327   17.00895069106943
C         3.01846247354776   10.96564420193701   15.80400089350625
F         1.01108018151314    7.97574153884706   15.80033300315082
F         2.31032290059799    7.66744311344969   18.10909871588842
F         4.11245334235870    9.54052191108612   18.95829735398827
F         4.54921654069228   11.77071611784559   17.42811313326906
F         3.23486047484227   12.09714459392873   15.11369692648162
H         5.76807689673631    9.73619390647207    8.23629657405553
```

2. start `xtb` with (all the options here)
`xtb AJUQAZ.xyz --chrg -1 --gfn 1 --scc`

3. run `xtb` with your options and the `--verbose` flag

4. output showing the error

Output with --verbose flag:

```
 * started run on 2020/10/19 at 15:02:49.167     

           -------------------------------------------------
          |                Calculation Setup                |
           -------------------------------------------------

          program call               : xtb AJUQAZ.xyz --chrg -1 --gfn 1 --scc --verbose
          coordinate file            : AJUQAZ.xyz
          xtbhome directory          : /home/andersx
          path for xtb               : /home/andersx
          xcontrol input file        : AJUQAZ.xyz
          omp threads                :                     6
          number of atoms            :                   106
          number of electrons        :                   346
          charge                     :                    -1
          spin                       :                   0.0
          first test random number   :      0.01459433815784
          a pointer address          :            0x3C6F1D17
          random memory content      :      3F8DE3A2E8C1E9C0

$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
 CONSTRAINTS & SCANS: DEBUG SECTION
$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
   ID    Z sym.   atoms
    1   74 W      1
    2    6 C      2, 4, 6-11, 15, 19, 23, 27, 32, 36, 40, 44, 48, 52, 56, 60,
                  64, 68, 73-78, 84-89, 95-100
    3    8 O      3, 5
    4    1 H      12-14, 16-18, 20-22, 24-26, 28-30, 37-39, 41-43, 45-47,
                  49-51, 53-55, 57-59, 61-63, 65-67, 69-71, 106
    5   14 Si     31, 33-35
    6    5 B      72
    7    9 F      79-83, 90-94, 101-105
$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$

molecular fragmentation (1/2 indicates fragments):
111111111111111111111111111111222222222222222222222222222222222222222221
1111111111111111111111111111111112
# atoms in fragment 1/2:    64    42
 fragment masses (1/2) :      887.07      260.67
CMA distance (Bohr)    :  11.251
constraining FC (au)   :  0.0500

           -------------------------------------------------
          |                 G F N 1 - x T B                 |
           -------------------------------------------------

        Reference                      10.1021/acs.jctc.7b00118
      * Hamiltonian:
        H0-scaling (s, p, d)           1.850000    2.250000    2.000000
        zeta-weighting                 0.000000
      * Dispersion:
        s8                             2.400000
        a1                             0.630000
        a2                             5.000000
        s9                             0.000000
      * Repulsion:
        kExp                           1.500000
        rExp                           1.000000
      * Coulomb:
        alpha                          2.000000
        third order                    atomic
        anisotropic                    false
      * Halogen bond correction:
        rad-scale                      1.300000
        damping                        0.440000


          ...................................................
          :                      SETUP                      :
          :.................................................:
          :  # basis functions                 368          :
          :  # atomic orbitals                 363          :
          :  # shells                          217          :
          :  # electrons                       346          :
          :  # halogen bonds                     0          :
          :  max. iterations                   250          :
          :  Hamiltonian                  GFN1-xTB          :
          :  restarted?                      false          :
          :  GBSA solvation                  false          :
          :  PC potential                    false          :
          :  electronic temp.          300.0000000     K    :
          :  accuracy                    1.0000000          :
          :  -> integral cutoff          0.2500000E+02      :
          :  -> integral neglect         0.1000000E-07      :
          :  -> SCF convergence          0.1000000E-05 Eh   :
          :  -> wf. convergence          0.2000000E-04 e    :
          :  Broyden damping             0.4000000          :
          ...................................................
Segmentation fault (core dumped)
```

**Expected behaviour**

**Additional context**

My xTB version is:
```
      -----------------------------------------------------------      
     |                   =====================                   |     
     |                           x T B                           |     
     |                   =====================                   |     
     |                         S. Grimme                         |     
     |          Mulliken Center for Theoretical Chemistry        |     
     |                    University of Bonn                     |     
      -----------------------------------------------------------      

   * xtb version 6.3.3 (7355c4f) compiled by 'conda@14e9545d6667' on 2020-09-17

normal termination of xtb
```

**Comment by awvwgk** [comment] 2020-10-19 14:21
I guess you experience this kind of crash only for a certain system size? The uninformative `Segmentation fault` is usually an OpenMP stackoverflow, which can happen due to insufficent memory available for the OpenMP parallelisation (`OMP_STACKSIZE` not set or not set to a reasonable large number). It might also happen to be just a normal stackoverflow, which means the system stack is too small, increase the system stack size with `ulimit -s unlimited`.

For more details on this see: https://xtb-docs.readthedocs.io/en/latest/setup.html#setting-up-xtb

**Comment by awvwgk** [comment] 2020-10-19 14:23
Duplicate of #191, #303

**Closed** 2020-10-19 14:32 UTC
Labels: duplicate
