### ISSUE TITLE
conda xtb segfaults when using gnu openmp and mkl

### ISSUE THREAD

**Issue by mattchan-tencent** [grimme-lab/xtb#557] opened 2022-01-07 07:33 UTC
**Describe the bug**
The xtb build in Conda segfaults when using _openmp_mutex=*gnu and mkl. It must use _openmp_mutex=*llvm to succeed.

**To Reproduce**
`conda install -c conda-forge xtb mkl "_openmp_mutex=*=*gnu"`

`xtb <test.xyz> --opt`

**Additional context**
Conda builds should really default to mkl. The openblas multithreading performance is really broken. See #401 for example.

**Comment by awvwgk** [comment] 2022-01-07 10:16
Maybe because I have `gomp` in host requires, will do a rebuild in https://github.com/conda-forge/xtb-feedstock/pull/24 with `gomp` in build requires as intended.

**Comment by awvwgk** [comment] 2022-01-07 14:43
Actually this combination is not supported by conda-forge:

```
❯ mamba create -n xtb xtb 'libblas=*=*mkl*' '_openmp_mutex=*=*gnu*'
...

Looking for: ['xtb', 'libblas=[build=*mkl*]', '_openmp_mutex=[build=*gnu*]']

conda-forge/linux-64     Using cache
conda-forge/noarch       Using cache
Encountered problems while solving:
  - nothing provides mkl 2019.1.* needed by libblas-3.8.0-4_mkl

❯ mamba create -n xtb xtb 'libblas=*=*mkl*'
...

Looking for: ['xtb', 'libblas=[build=*mkl*]']

conda-forge/linux-64     Using cache
conda-forge/noarch       Using cache
Transaction

  Prefix: /home/awvwgk/software/opt/conda/envs/xtb

  Updating specs:

   - xtb
   - libblas=*[build=*mkl*]


  Package            Version  Build           Channel                    Size
───────────────────────────────────────────────────────────────────────────────
  Install:
───────────────────────────────────────────────────────────────────────────────

  + _libgcc_mutex        0.1  conda_forge     conda-forge/linux-64     Cached
  + _openmp_mutex        4.5  1_llvm          conda-forge/linux-64     Cached
  + libblas            3.9.0  12_linux64_mkl  conda-forge/linux-64     Cached
  + libgcc-ng         11.2.0  h1d223b6_11     conda-forge/linux-64     Cached
  + libgfortran-ng    11.2.0  h69a702a_11     conda-forge/linux-64     Cached
  + libgfortran5      11.2.0  h5c6108e_11     conda-forge/linux-64     Cached
  + liblapack          3.9.0  12_linux64_mkl  conda-forge/linux-64     Cached
  + libstdcxx-ng      11.2.0  he4da1e4_11     conda-forge/linux-64     Cached
  + llvm-openmp       12.0.1  h4bd325d_1      conda-forge/linux-64     Cached
  + mkl             2021.4.0  h8d4b97c_729    conda-forge/linux-64     Cached
  + tbb             2021.5.0  h4bd325d_0      conda-forge/linux-64     Cached
  + xtb                6.4.1  hf06ca72_2      conda-forge/linux-64     Cached

  Summary:

  Install: 12 packages

  Total download: 0  B

───────────────────────────────────────────────────────────────────────────────

Confirm changes: [Y/n] y
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate xtb
#
# To deactivate an active environment, use
#
#     $ conda deactivate
❯ conda activate xtb
❯ mamba install '_openmp_mutex=*=*gnu*'
...

Looking for: ['_openmp_mutex=[build=*gnu*]']

conda-forge/linux-64     Using cache
conda-forge/noarch       Using cache
Encountered problems while solving:
  - package mkl-2021.4.0-h8d4b97c_729 requires _openmp_mutex * *_llvm, but none of the providers can be installed


```

**Comment by awvwgk** [comment] 2022-01-10 21:09
I think this issue is now resolved with the rebuild. Feel free to reopen in case this issue is not resolved yet.

**Closed by awvwgk** 2022-01-10 21:09 UTC
