### ISSUE TITLE
xtb library was not found in your LD_LIBRARY_PATH

### ISSUE THREAD

**Issue by ekwan** [grimme-lab/xtb#176] opened 2020-04-23 20:41 UTC
Hi everyone, thanks for helping so quickly.  I have another problem now, which is that the Python interface isn't working.

```
~/software/xtb $ more test.py
import ctypes
from ctypes import cdll

try:
   xtb = cdll.LoadLibrary('libxtb.so')
except OSError:
   print("xtb library was not found in your LD_LIBRARY_PATH")
~/software/xtb $ python test.py
xtb library was not found in your LD_LIBRARY_PATH

xtb library was not found in your LD_LIBRARY_PATH
```

The documentation recommends `ninja install` but doesn't specify where to do it from.  I installed ninja from homebrew, but then I get:

```
 ~/software/xtb/build $ ninja install
ninja: error: loading 'build.ninja': No such file or directory
```

I already ran pip install from the python folder.  What did I miss?  Thanks.
```

**Comment by awvwgk** [comment] 2020-04-23 21:26
And I should definitely flag the Python documentation as out-of-date and rewrite them at some point.

**Comment by ekwan** [comment] 2020-04-23 21:58
Well...I did run `make install`.  Here's an error I'm getting when I try to call xtb from Python:

```
Traceback (most recent call last):
  File "/Users/ekwan/research/presto/test/test_calculator.py", line 74, in test_xtb
    results = xtb.interface.XTBLibrary().GFN2Calculation(
  File "/Users/ekwan/anaconda2/envs/presto/lib/python3.8/site-packages/xtb-6.2.3-py3.8.egg/xtb/interface.py", line 225, in __init__
    self.library = load_library('libxtb')
  File "/Users/ekwan/anaconda2/envs/presto/lib/python3.8/site-packages/xtb-6.2.3-py3.8.egg/xtb/interface.py", line 69, in load_library
    return cdll.LoadLibrary(libname_ext)
  File "/Users/ekwan/anaconda2/envs/presto/lib/python3.8/ctypes/__init__.py", line 451, in LoadLibrary
    return self._dlltype(name)
  File "/Users/ekwan/anaconda2/envs/presto/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(libxtb.dylib, 6): image not found
```

Adding various paths to LD_LIBRARY_PATH doesn't seem to do anything.

**Comment by ekwan** [comment] 2020-04-24 05:01
I don't know if this helps, but:

```
$ ls -l /Users/ekwan/.local/lib
total 21904
-rwxr-xr-x 1 ekwan staff 10662952 Apr 23 12:59 libxtb_shared.dylib
-rw-r--r-- 1 ekwan staff 11760728 Apr 23 23:05 libxtb_static.a
```

**Comment by awvwgk** [comment] 2020-04-24 06:26
This is actually helping, the library is apparently named `libxtb_shared.dylib`, so you either rename to `libxtb.dylib` or construct your calculator with
```python
import ctypes
import xtb.interface
import xtb.calculator
calc = GFN2(library=XTBLibrary(library=ctypes.CDLL('libxtb_shared.dylib')))
```

**Comment by ekwan** [comment] 2020-04-24 12:34
Thanks!  The imports there don't quite work, but this worked:

```
import ctypes

import xtb
from xtb import GFN2
from xtb.interface import XTBLibrary

library = ctypes.CDLL('/Users/ekwan/.local/lib/libxtb_shared.dylib')
library = XTBLibrary(library)
calc = GFN2(library=library)
print("ok")
```

What went wrong, though?  It seems like it might a simple fix--getting xtb to look in a few standard places?  Here's what I got from `make install`:

```
~/software/xtb/build $ make install
[ 84%] Built target xtb_object
[ 84%] Built target xtb_shared
[ 91%] Built target xtb_tests_shared
[ 91%] Built target xtb_static
[ 99%] Built target xtb_tests_static
[100%] Built target xtb_tests_capi
[100%] Built target xtb
Install the project...
-- Install configuration: "Release"
-- Up-to-date: /Users/ekwan/.local/include/xtb/xtb.h
-- Up-to-date: /Users/ekwan/.local/share/xtb/.param_gfn0.xtb
-- Up-to-date: /Users/ekwan/.local/share/xtb/.param_gfn.xtb
-- Up-to-date: /Users/ekwan/.local/share/xtb/.param_gfn2.xtb
-- Installing: /Users/ekwan/.local/lib/libxtb_static.a
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: /Users/ekwan/.local/lib/libxtb_static.a(accuracy.f90.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: /Users/ekwan/.local/lib/libxtb_static.a(convert.f90.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: /Users/ekwan/.local/lib/libxtb_static.a(io.f90.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: /Users/ekwan/.local/lib/libxtb_static.a(thresholds.f90.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: /Users/ekwan/.local/lib/libxtb_static.a(version.f90.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: /Users/ekwan/.local/lib/libxtb_static.a(mctc_constants.f90.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: /Users/ekwan/.local/lib/libxtb_static.a(mctc_param.f90.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: /Users/ekwan/.local/lib/libxtb_static.a(lapack.f90.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: /Users/ekwan/.local/lib/libxtb_static.a(blas.f90.o) has no symbols
-- Installing: /Users/ekwan/.local/lib/libxtb_shared.dylib
-- Up-to-date: /Users/ekwan/.local/bin/xtb
-- Up-to-date: /Users/ekwan/.local/share/cmake/xtb/xtbConfig.cmake
-- Up-to-date: /Users/ekwan/.local/share/cmake/xtb/xtbConfigVersion.cmake
-- Up-to-date: /Users/ekwan/.local/share/cmake/xtb/xtbTargets.cmake
-- Up-to-date: /Users/ekwan/.local/share/cmake/xtb/xtbTargets-release.cmake
```

Thanks again for all the help.

**Comment by awvwgk** [comment] 2020-04-24 13:09
The problem is, it is not `xtb` looking for the shared object but `ld` and `ldconfig`, which are bound by other rules and somewhat out of reach for me from the Python side. You should check if `ldconfig` is allowed to load libraries from your `$HOME/.local/lib` directory, than again I find the non-standard name CMake gives the `dylib` strange.

Unfortunately, it does this also the case for Linux on the Travis-CI server and this might be indeed another bug with the CMake build system:
https://travis-ci.com/github/grimme-lab/xtb/jobs/322865378#L1259

If you do not have a strong preference for CMake I would suggest using meson as it is the more stable build system for `xtb` and also covers more of its features. Unfortunately, I just noticed that the meson 0.54 release is broken for OSX, but at least the 0.53.x worked just fine.

**Comment by ekwan** [comment] 2020-04-24 13:23
OK, well unfortunately, I don't have the intel compiler (and it's not free).  Is there a way to use meson with gfortran/gcc?

I also tried just installing from the tarball.  I just ran `pip install .` from the `python` folder.  I get the same library error.

**Comment by awvwgk** [comment] 2020-04-24 13:27
meson builds with GCC as well, it is not limited to Intel compilers.

Just export `FC=gfortran` and `CC=gcc`, but make sure the GCC is not the OSX `clang` but the real GCC. You might have to set the `CC` variable to `gcc-8` or `gcc-9` depending on the brew formula installed.

**Comment by ekwan** [comment] 2020-04-24 13:36
Ah, OK!  What do I do for this line?

```
meson setup build_intel --buildtype release --optimization=2
```

I have good news though.  I started over with a clean conda environment and `conda install xtb` worked!

```
~/software $ xtb --version
      -----------------------------------------------------------
     |                   =====================                   |
     |                           x T B                           |
     |                   =====================                   |
     |                         S. Grimme                         |
     |          Mulliken Center for Theoretical Chemistry        |
     |                    University of Bonn                     |
      -----------------------------------------------------------

   * xtb version 6.2.3 (conda-forge) compiled by 'runner@Mac-1266.local' on

normal termination of xtb
```

I then cloned the xtb repo and ran `pip install .` and that seemed to work.  However, this code does not work:

```
    def test_xtb(self):
        #Adapted from https://github.com/grimme-lab/xtb/blob/master/python/xtb/test/test_interface.py
        natoms = 24
        numbers = np.array(
            [6, 7, 6, 7, 6, 6, 6, 8, 7, 6, 8, 7, 6, 6, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
            dtype=c_int,
        )
        positions = np.array(
            [
                [2.02799738646442, 0.09231312124713, -0.14310895950963],
                [4.75011007621000, 0.02373496014051, -0.14324124033844],
                [6.33434307654413, 2.07098865582721, -0.14235306905930],
                [8.72860718071825, 1.38002919517619, -0.14265542523943],
                [8.65318821103610, -1.19324866489847, -0.14231527453678],
                [6.23857175648671, -2.08353643730276, -0.14218299370797],
                [5.63266886875962, -4.69950321056008, -0.13940509630299],
                [3.44931709749015, -5.48092386085491, -0.14318454855466],
                [7.77508917214346, -6.24427872938674, -0.13107140408805],
                [10.30229550927022, -5.39739796609292, -0.13672168520430],
                [12.07410272485492, -6.91573621641911, -0.13666499342053],
                [10.70038521493902, -2.79078533715849, -0.14148379504141],
                [13.24597858727017, -1.76969072232377, -0.14218299370797],
                [7.40891694074004, -8.95905928176407, -0.11636933482904],
                [1.38702118184179, 2.05575746325296, -0.14178615122154],
                [1.34622199478497, -0.86356704498496, 1.55590600570783],
                [1.34624089204623, -0.86133716815647, -1.84340893849267],
                [5.65596919189118, 4.00172183859480, -0.14131371969009],
                [14.67430918222276, -3.26230980007732, -0.14344911021228],
                [13.50897177220290, -0.60815166181684, 1.54898960808727],
                [13.50780014200488, -0.60614855212345, -1.83214617078268],
                [5.41408424778406, -9.49239668625902, -0.11022772492007],
                [8.31919801555568, -9.74947502841788, 1.56539243085954],
                [8.31511620712388, -9.76854236502758, -1.79108242206824],
            ],
            dtype=c_double,
        )

        options = {
            "print_level": 0,
            "parallel": 0,
            "accuracy": 1.0,
            "electronic_temperature": 300.0,
            "gradient": True,
            "restart": False,
            "ccm": True,
            "max_iterations": 30,
            "solvent": "ch2cl2",
        }

        results = xtb.interface.XTBLibrary().GFN2Calculation(
            natoms=natoms,
            numbers=numbers,
            charge=0.0,
            positions=positions,
            options=options,
            output="-",
            magnetic_moment=0,
        )

        self.assertTrue((results["energy"] + 42.170585 ) < 0.001)
```

This is the error I get:

```
Solvent             : ch2cl2
 Using internal parameter file: .param_gbsa2_ch2cl2
 Gsolv ref. state (COSMO-RS): gsolv [1 M gas/solution]
 temperature (mdtemp)       :    300.00000000000000
 dielectric constant        :    8.9299999999999997
 rho                        :    1.3300000000000003
 mass                       :    84.930000000000007
 surface tension            :    15.568945408385856
 probe radius               :   0.71987590000000001
 Gshift (Eh)                :    4.4408291734517593E-003
 c1                         :    1.4917377599999999
 soset                      :    0.0000000000000000
 HB correction              :  F
 no basis found for atom          24  Z=            0
abnormal termination of peeq
ERROR STOP
```

It seems like it's not reading the atomic numbers for some reason.  Thoughts?  Thanks a lot.

**Comment by ekwan** [comment] 2020-04-24 13:43
Ah, problem fixed with this:

**Comment by awvwgk** [comment] 2020-04-24 13:45
> Ah, OK! What do I do for this line?
> 
> ```
> meson setup build_intel --buildtype release --optimization=2
> ```
> 
This should usually work fine already, except that the build directory is called `build_intel` for a GCC build

```
FC=gfortran CC=gcc-8 meson setup build --buildtype release --optimization=2
```

**Comment by ekwan** [comment] 2020-04-24 13:47
Oh man, maybe I spoke too soon!  So most of the time when I run that test, I get an energy of:

```
-42.17010949703972
```

However, occasionally I get:

```
-41.68825289175895
```

I'm baffled!

**Comment by awvwgk** [comment] 2020-04-24 13:48
Please refer to the [setup guide](https://xtb-docs.readthedocs.io/en/latest/setup.html#environment-variables-for-xtb) where the necessary environment setup for `xtb` is explained in detail. Of course it also applies if you are using the python bindings because it is using the same implementation under the hood.

**Comment by ekwan** [comment] 2020-04-24 14:06
Interestingly, the test didn't fail after I ran it 200 times in a row.  However, when I ran two consecutive tests over and over, the second test failed about 3% of the time.  Occasionally, I get nan; other times I get a weird energy.  Sometimes I got a `malloc` error.  I wonder if there's an issue with initializing xtb's memory spaces properly when a calculation is run right after another one.

**Comment by awvwgk** [comment] 2020-04-24 14:09
We have a small stability problem with the API, this is known and I'm working on a fix, which unfortunately will break the API compatibility. But this is something I will tackle after the 6.3 release.

**Comment by ekwan** [comment] 2020-04-24 16:04
Thank you so much for your help!  This works well enough for now and we will upgrade when you release again.  I know it's probably quite a bit of work, but streamlining the installation process and updating the clarity of the instructions would be very useful.  We'd be very happy to try out any updated installation procedures.

**Comment by awvwgk** [comment] 2020-05-11 15:36
Should be fixed with the conda-forge update in https://github.com/conda-forge/xtb-feedstock/pull/3

**Closed by awvwgk** 2020-05-11 15:36 UTC
Labels: documentation, python
