### ISSUE TITLE
Topology missing in xtbtopo.mol file

### ISSUE THREAD

**Issue by GES-lbabetto** [grimme-lab/xtb#647] opened 2022-06-15 15:55 UTC
From 6.5.0, the xtbtopo.mol no longer contains bond information for the optimized structure, but only coordinates.

xtb 6.5.0 installed via Conda on a workstation running Ubuntu 20.04. Also reproduced on a WSL2 environment with the Conda installation.

**Steps to reproduce the behaviour:**

Carry out a geometry optimization on any molecule, with the command:

```
xtb test.xyz -o
```

**Expected behaviour**

The xtbtopo.mol file should contain bond information:

```

  xtb     12212112303D
 xtb: 6.4.1 (afa7bdf)
 21 21  0     0  0            999 V2000
   -0.0167    2.1162   -0.0001 C   0  0  0  0  0  0  0  0  0  0  0  0
   -1.2153    1.4265   -0.0008 C   0  0  0  0  0  0  0  0  0  0  0  0
   -1.2187    0.0368   -0.0002 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.0008   -0.6505   -0.0005 C   0  0  0  0  0  0  0  0  0  0  0  0
    1.2046    0.0612   -0.0005 C   0  0  0  0  0  0  0  0  0  0  0  0
    1.1941    1.4482    0.0005 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.0059   -2.0159   -0.0002 O   0  0  0  0  0  0  0  0  0  0  0  0
   -2.3366   -0.7500    0.0007 O   0  0  0  0  0  0  0  0  0  0  0  0
   -3.6003   -0.1158    0.0005 C   0  0  0  0  0  0  0  0  0  0  0  0
    2.3321   -0.7286   -0.0009 O   0  0  0  0  0  0  0  0  0  0  0  0
    3.5948   -0.0924    0.0011 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.9151   -2.3248    0.0013 H   0  0  0  0  0  0  0  0  0  0  0  0
   -2.1420    1.9745   -0.0017 H   0  0  0  0  0  0  0  0  0  0  0  0
   -0.0270    3.1944   -0.0000 H   0  0  0  0  0  0  0  0  0  0  0  0
   -3.7339    0.4999    0.8938 H   0  0  0  0  0  0  0  0  0  0  0  0
   -3.7357    0.4953   -0.8956 H   0  0  0  0  0  0  0  0  0  0  0  0
   -4.3240   -0.9275    0.0034 H   0  0  0  0  0  0  0  0  0  0  0  0
    3.7258    0.5262   -0.8904 H   0  0  0  0  0  0  0  0  0  0  0  0
    3.7270    0.5165    0.8987 H   0  0  0  0  0  0  0  0  0  0  0  0
    4.3215   -0.9015   -0.0039 H   0  0  0  0  0  0  0  0  0  0  0  0
    2.1142    2.0075    0.0013 H   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  4  0  0  0  0
  2  3  4  0  0  0  0
  3  4  4  0  0  0  0
  4  5  4  0  0  0  0
  1  6  4  0  0  0  0
  5  6  4  0  0  0  0
  4  7  1  0  0  0  0
  3  8  1  0  0  0  0
  8  9  1  0  0  0  0
  5 10  1  0  0  0  0
 10 11  1  0  0  0  0
  7 12  1  0  0  0  0
  2 13  1  0  0  0  0
  1 14  1  0  0  0  0
  9 15  1  0  0  0  0
  9 16  1  0  0  0  0
  9 17  1  0  0  0  0
 11 18  1  0  0  0  0
 11 19  1  0  0  0  0
 11 20  1  0  0  0  0
  6 21  1  0  0  0  0
M  END
```

In 6.5.0, only contains the coordinates:

```
 xtb: 6.5.0 (97a52f5)
          06152217493D

 21  0  0     0  0            999 V2000
   -0.0167    2.1162   -0.0001 C   0  0  0  0  0  0  0  0  0  0  0  0
   -1.2153    1.4265   -0.0008 C   0  0  0  0  0  0  0  0  0  0  0  0
   -1.2187    0.0368   -0.0002 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.0008   -0.6505   -0.0005 C   0  0  0  0  0  0  0  0  0  0  0  0
    1.2046    0.0612   -0.0005 C   0  0  0  0  0  0  0  0  0  0  0  0
    1.1941    1.4482    0.0005 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.0059   -2.0159   -0.0002 O   0  0  0  0  0  0  0  0  0  0  0  0
   -2.3366   -0.7500    0.0007 O   0  0  0  0  0  0  0  0  0  0  0  0
   -3.6003   -0.1158    0.0005 C   0  0  0  0  0  0  0  0  0  0  0  0
    2.3321   -0.7286   -0.0009 O   0  0  0  0  0  0  0  0  0  0  0  0
    3.5948   -0.0924    0.0011 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.9151   -2.3248    0.0013 H   0  0  0  0  0  0  0  0  0  0  0  0
   -2.1420    1.9745   -0.0017 H   0  0  0  0  0  0  0  0  0  0  0  0
   -0.0270    3.1944   -0.0000 H   0  0  0  0  0  0  0  0  0  0  0  0
   -3.7339    0.4999    0.8938 H   0  0  0  0  0  0  0  0  0  0  0  0
   -3.7357    0.4953   -0.8956 H   0  0  0  0  0  0  0  0  0  0  0  0
   -4.3240   -0.9275    0.0034 H   0  0  0  0  0  0  0  0  0  0  0  0
    3.7258    0.5262   -0.8904 H   0  0  0  0  0  0  0  0  0  0  0  0
    3.7270    0.5165    0.8987 H   0  0  0  0  0  0  0  0  0  0  0  0
    4.3215   -0.9015   -0.0039 H   0  0  0  0  0  0  0  0  0  0  0  0
    2.1142    2.0075    0.0013 H   0  0  0  0  0  0  0  0  0  0  0  0
M  END
```

Attached files:

- test.xyz file used for the calculation
- output file for 6.4.1 (giving the correct behaviour)
- output file for 6.5.0
- xtbtopo.mol file from 6.4.1
- xtbtopo.mol file from 6.5.0

[files.zip](https://github.com/grimme-lab/xtb/files/8911069/files.zip)

**Comment by awvwgk** [comment] 2022-06-15 18:41
Duplicate of https://github.com/grimme-lab/xtb/issues/628

**Closed** 2022-06-15 18:41 UTC
Labels: duplicate
