### ISSUE TITLE
Unable to limit distance of two bonds at the same time when doing MD with GFN0-xtb

### ISSUE THREAD

**Issue by Mercury-Lamp** [grimme-lab/xtb#844] opened 2023-08-13 08:04 UTC
**Describe the bug**
I want to constrain the distance of two bonds while doing a molecular dynamics simulation with GFN0-xtb, but I found that only one constraint is effective. Maybe the problem is in my input file, but in the official documentation I didn't find how to limit the distance of two bonds at the same time.

**To Reproduce**
Steps to reproduce the behaviour:

1. start xtb (version 6.6.1) with: 
`xtb input.xyz --input md.inp --md --gfn 0`
2. In the output, I found: 
`constraining bond 29 102 to    1.2400000 Å, actual value:    1.2400078 Å`
`constraining bond 60 102 to    1.1400000 Å, actual value:    1.1400095 Å`
3. But when I used VMD to observe the trajectory, I found that only "constraining bond 60 102 to    1.1400000 Å, actual value:    1.1400095 Å" is in effect.

**Expected behaviour**
I hopt both constraints in the input file to be in effect at the same time.

**Additional context**
I also tried writing this in the input file:
```
$constrain
   DISTANCE: 29, 102, 1.24; 60, 102, 1.14
$end
```
but this also didn't work

**Input and generated files**
[xtb-MD.zip](https://github.com/grimme-lab/xtb/files/12329026/xtb-MD.zip)

**Comment by MtoLStoN** [comment] 2023-08-17 10:12
Hi @Mercury-Lamp,

it seems, that the default force constant is just not strong enough to enforce your constraint. You could try constraining the atoms more tightly by using for example
```
$constrain
   distance: 29, 102, 1.24
   distance: 60, 102, 1.14
   force constant=1.0
$end
```
Let me know, if this works for you.

**Comment by Mercury-Lamp** [comment] 2023-08-18 13:55
> Hi @Mercury-Lamp,
> 
> it seems, that the default force constant is just not strong enough to enforce your constraint. You could try constraining the atoms more tightly by using for example
> 
> ```
> $constrain
>    distance: 29, 102, 1.24
>    distance: 60, 102, 1.14
>    force constant=1.0
> $end
> ```
> 
> Let me know, if this works for you.

Hi @MtoLStoN ,
Thank you for your suggestion. When I increase the force constant to 1.0, both constraints appear to be working (although there are still some fluctuations in the distance between atoms 60 and 102, when I continue to increase the force constant, this fluctuation can be almost ignored).

Thank you again for your help.

**Comment by MtoLStoN** [comment] 2023-08-18 14:02
Hi @Mercury-Lamp,
Thanks for confirming. From a technical perspective, everything appears to be working as intended. Consequently, I will close this issue. If anything else comes up, we can always follow up in another issue.
Best
Marcel

**Closed by MtoLStoN** 2023-08-18 14:02 UTC
Labels: support
