### ISSUE TITLE
OpenMP stackoverflow due to insufficient OMP_STACKSIZE

### ISSUE THREAD

**Issue by ekwan** [grimme-lab/xtb#191] opened 2020-05-10 19:53 UTC
Hello, thanks again for helping so much with xtb troubleshooting.  Today's problem is with running GFN0 in larger systems.  Here's my setup:

```
$ printenv | grep -i 'OMP_\|MKL\|XTB'
OMP_MAX_ACTIVE_LEVELS=1
OMP_STACKSIZE=1G
XTBHOME=/Users/ekwan/anaconda2/envs/presto/share/xtb
XTBPATH=/Users/ekwan/anaconda2/envs/presto/share/xtb
MKL_NUM_THREADS=4
OMP_NUM_THREADS=4,1

(presto) $ xtb --version
      -----------------------------------------------------------
     |                   =====================                   |
     |                           x T B                           |
     |                   =====================                   |
     |                         S. Grimme                         |
     |          Mulliken Center for Theoretical Chemistry        |
     |                    University of Bonn                     |
      -----------------------------------------------------------

   * xtb version 6.2.3 (conda-forge) compiled by 'runner@Mac-1266.local' on

normal termination of xtb
```

OK, and here's what happens with GFN-2:

```
(presto) $ xtb --gfn 2 solvated-brettphos-pd.xyz
...
 * started run on 2020/05/10 at 15:41:22.383

           -------------------------------------------------
          |                Calculation Setup                |
           -------------------------------------------------

          program call               : xtb --gfn 2 solvated-brettphos-pd.xyz
          coordinate file            : solvated-brettphos-pd.xyz
          omp threads                :                     4
          number of atoms            :                  1392
          number of electrons        :                  3220
          charge                     :                     0
          spin                       :                   0.0
          first test random number   :      0.20342827877638


molecular fragmentation (1/2 indicates fragments):
111111111111111111111111111111111111111111111111111111111111111111111111
111111111111111111112222222222222222222222222222222222222222222222222222
222222222222222222222222222222222222222222222222222222222222222222222222
222222222222222222222222222222222222222222222222222222222222222222222222
222222222222222222222222222222222222222222222222222222222222222222222222
222222222222222222222222222222222222222222222222222222222222222222222222
222222222222222222222222222222222222222222222222222222222222222222222222
222222222222222222222222222222222222222222222222222222222222222222222222
222222222222222222222222222222222222222222222222222222222222222222222222
222222222222222222222222222222222222222222222222222222222222222222222222
222222222222222222222222222222222222222222222222222222222222222222222222
222222222222222222222222222222222222222222222222222222222222222222222222
222222222222222222222222222222222222222222222222222222222222222222222222
222222222222222222222222222222222222222222222222222222222222222222222222
222222222222222222222222222222222222222222222222222222222222222222222222
222222222222222222222222222222222222222222222222222222222222222222222222
222222222222222222222222222222222222222222222222222222222222222222222222
222222222222222222222222222222222222222222222222222222222222222222222222
222222222222222222222222222222222222222222222222222222222222222222222222
222222222222222222222222
# atoms in fragment 1/2:    92  1300
 fragment masses (1/2) :      643.18     7210.59
CMA distance (Bohr)    :   1.411
constraining FC (au)   :  0.0500
           -------------------------------------------------
          |                 G F N 2 - x T B                 |
          | Geometry, Frequencies, Noncovalent interactions |
          |            JCTC 2019 parametrisation            |
           -------------------------------------------------
             k(s)              :                1.8500
             k(p)              :                2.2300
             k(d)              :                2.2300
             k(f)              :                2.0000
             kEN (H0ij)        :               -2.0000
             D4 a1             :                0.5200
             D4 a2             :                5.0000
             D4 s6             :                1.0000
             D4 s8             :                2.7000
             D4 s9             :                5.0000
             alphaj            :                2.0000

  Z AO/shell   Hii/eV     exponent
  1     Wed Apr 25 08:07:45 CEST 2018   EN: 2.200 GM2: 0.406  GM3: 0.0800  RAES: 1.40
     1s    -10.707211    1.230000
  6     Wed Apr 25 08:07:45 CEST 2018   EN: 2.550 GM2: 0.538  GM3: 0.1500  RAES: 3.00
     2s    -13.970922    2.096432
     2p    -10.063292    1.800000
  8     Wed Apr 25 08:07:45 CEST 2018   EN: 3.440 GM2: 0.452  GM3:-0.0517  RAES: 1.80
     2s    -20.229985    2.439742
     2p    -15.503117    2.137023
 15     Mon Apr 23 19:31:07 CEST 2018   EN: 2.190 GM2: 0.298  GM3: 0.0711  RAES: 2.10
     3s    -17.518756    1.816945
     3p     -9.842286    1.903247
     3d     -0.444893    1.167533
 46     Wed Apr 25 16:26:58 CEST 2018   EN: 2.200 GM2: 0.273  GM3: 0.0800  RAES: 5.00
     4d    -11.963518    2.353691
     5s     -9.714059    1.828354
     5p     -2.035281    1.333352

           -------------------------------------------------
          |        Self-Consistent Charge Iterations        |
           -------------------------------------------------

          ...................................................
          :                      SETUP                      :
          :.................................................:
          :  # basis functions                3021          :
          :  # atomic orbitals                3019          :
          :  # shells                         1933          :
          :  # electrons                      3220          :
          :  max. iterations                   250          :
          :  Hamiltonian                  GFN2-xTB          :
          :  restarted?                      false          :
          :  GBSA solvation                  false          :
          :  PC potential                    false          :
          :  electronic temp.          300.0000000     K    :
          :  accuracy                    1.0000000          :
          :  -> integral cutoff          0.2500000E+02      :
          :  -> integral neglect         0.1000000E-07      :
          :  -> SCF convergence          0.1000000E-05 Eh   :
          :  -> wf. convergence          0.1000000E-03 e    :
          :  Broyden damping             0.4000000          :
          ...................................................

 iter      E             dE          RMSdq      gap      omega  full diag
   1  -1801.4085801 -0.180141E+04  0.389E+00    3.08       0.0  T
   2  -1805.2088587 -0.380028E+01  0.207E+00    2.64       1.0  T
   3  -1805.2441491 -0.352904E-01  0.869E-01    1.68       1.0  T
   4  -1805.2168202  0.273288E-01  0.232E-01    1.91       1.0  T
   5  -1805.2770833 -0.602631E-01  0.112E-01    1.77       1.0  T
   6  -1805.2853511 -0.826772E-02  0.529E-02    1.87       1.0  T
   7  -1805.2860130 -0.661899E-03  0.231E-02    1.91       1.0  T
   8  -1805.2862342 -0.221187E-03  0.103E-02    1.90       1.0  T
   9  -1805.2862432 -0.907881E-05  0.633E-03    1.89       1.0  T
  10  -1805.2862529 -0.965586E-05  0.342E-03    1.89       1.0  T
  11  -1805.2862553 -0.237306E-05  0.132E-03    1.89       2.0  T
  12  -1805.2862561 -0.817290E-06  0.634E-04    1.89       4.2  T
  13  -1805.2862562 -0.106017E-06  0.362E-04    1.89       7.4  T

   *** convergence criteria satisfied after 13 iterations ***

         #    Occupation            Energy/Eh            Energy/eV
      -------------------------------------------------------------
         1        2.0000           -0.7181517             -19.5419
       ...           ...                  ...                  ...
      1604        2.0000           -0.3316483              -9.0246
      1605        2.0000           -0.3304132              -8.9910
      1606        2.0000           -0.3166006              -8.6151
      1607        2.0000           -0.3139338              -8.5426
      1608        2.0000           -0.3113692              -8.4728
      1609        2.0000           -0.3087615              -8.4018
      1610        2.0000           -0.2937188              -7.9925 (HOMO)
      1611                         -0.2241198              -6.0986 (LUMO)
      1612                         -0.2007018              -5.4614
      1613                         -0.1914396              -5.2093
      1614                         -0.1886282              -5.1328
      1615                         -0.1310949              -3.5673
       ...                                ...                  ...
      3019                          1.9852379              54.0211
      -------------------------------------------------------------
                  HL-Gap            0.0695990 Eh            1.8939 eV
             Fermi-level           -0.2589193 Eh           -7.0456 eV

 SCC (total)                   0 d,  0 h,  2 min,  3.307 sec
 SCC setup                      ...        0 min,  0.418 sec (  0.339%)
 Dispersion                     ...        0 min,  0.721 sec (  0.585%)
 integral evaluation            ...        0 min,  8.416 sec (  6.826%)
 zeroth order Hamiltonian       ...        0 min,  0.085 sec (  0.069%)
 iterations                     ...        1 min, 24.648 sec ( 68.648%)
 molecular gradient             ...        0 min, 28.539 sec ( 23.145%)
 printout                       ...        0 min,  0.479 sec (  0.389%)

         :::::::::::::::::::::::::::::::::::::::::::::::::::::
         ::                     SUMMARY                     ::
         :::::::::::::::::::::::::::::::::::::::::::::::::::::
         :: total energy           -1787.333354194956 Eh    ::
         :: gradient norm              0.630358415560 Eh/a0 ::
         :: HOMO-LUMO gap              1.893883994040 eV    ::
         ::.................................................::
         :: SCC energy             -1805.286256186562 Eh    ::
         :: -> isotropic ES            2.112521849353 Eh    ::
         :: -> anisotropic ES          0.313206124045 Eh    ::
         :: -> anisotropic XC          0.642293181002 Eh    ::
         :: -> dispersion             -1.724395079918 Eh    ::
         :: repulsion energy          17.744217108470 Eh    ::
         :: add. restraining           0.000000000000 Eh    ::
         :::::::::::::::::::::::::::::::::::::::::::::::::::::

           -------------------------------------------------
          |                Property Printout                |
           -------------------------------------------------
...
           -------------------------------------------------
          | TOTAL ENERGY            -1787.333354194956 Eh   |
          | GRADIENT NORM               0.630358415560 Eh/α |
          | HOMO-LUMO GAP               1.893883994040 eV   |
           -------------------------------------------------

------------------------------------------------------------------------
 * finished run on 2020/05/10 at 15:43:41.060
------------------------------------------------------------------------
 total:
 * wall-time:     0 d,  0 h,  2 min, 18.675 sec
 *  cpu-time:     0 d,  0 h,  7 min, 35.972 sec
 * ratio c/w:     3.288 speedup
 SCF:
 * wall-time:     0 d,  0 h,  2 min,  3.409 sec
 *  cpu-time:     0 d,  0 h,  6 min, 55.445 sec
 * ratio c/w:     3.366 speedup

normal termination of xtb
Note: The following floating-point exceptions are signalling: IEEE_UNDERFLOW_FLAG IEEE_DENORMAL
```

OK that worked, but now after I clear the files and try GFN-0, it breaks:

```
(presto) $ xtb --gfn 0 --parallel 4 solvated-brettphos-pd.xyz
...
 * started run on 2020/05/10 at 15:44:18.805

           -------------------------------------------------
          |                Calculation Setup                |
           -------------------------------------------------

          program call               : xtb --gfn 0 --parallel 4 solvated-brettphos-pd.xyz
          coordinate file            : solvated-brettphos-pd.xyz
          omp threads                :                     4
          number of atoms            :                  1392
          number of electrons        :                  3220
          charge                     :                     0
          spin                       :                   0.0
          first test random number   :      0.20340046255056


molecular fragmentation (1/2 indicates fragments):
111111111111111111111111111111111111111111111111111111111111111111111111
111111111111111111112222222222222222222222222222222222222222222222222222
222222222222222222222222222222222222222222222222222222222222222222222222
222222222222222222222222222222222222222222222222222222222222222222222222
222222222222222222222222222222222222222222222222222222222222222222222222
222222222222222222222222222222222222222222222222222222222222222222222222
222222222222222222222222222222222222222222222222222222222222222222222222
222222222222222222222222222222222222222222222222222222222222222222222222
222222222222222222222222222222222222222222222222222222222222222222222222
222222222222222222222222222222222222222222222222222222222222222222222222
222222222222222222222222222222222222222222222222222222222222222222222222
222222222222222222222222222222222222222222222222222222222222222222222222
222222222222222222222222222222222222222222222222222222222222222222222222
222222222222222222222222222222222222222222222222222222222222222222222222
222222222222222222222222222222222222222222222222222222222222222222222222
222222222222222222222222222222222222222222222222222222222222222222222222
222222222222222222222222222222222222222222222222222222222222222222222222
222222222222222222222222222222222222222222222222222222222222222222222222
222222222222222222222222222222222222222222222222222222222222222222222222
222222222222222222222222
# atoms in fragment 1/2:    92  1300
 fragment masses (1/2) :      643.18     7210.59
CMA distance (Bohr)    :   1.411
constraining FC (au)   :  0.0500
########################################################################
[WARNING] Please study the warnings concerning your input carefully
-1- argparser_rdxargs: Process number higher than OMP_NUM_THREADS, I hope you know what you are doing.
########################################################################
           -------------------------------------------------
          |                 G F N 0 - x T B                 |
          | Geometry, Frequencies, Noncovalent interactions |
          |           preliminary parametrisation           |
           -------------------------------------------------
             KAB for M(3d)-M(3d)    :  1.1000
             KAB for M(4d)-M(4d)    :  1.1000
             KAB for M(5d)-M(5d)    :  1.1000
             KAB for M-M (group XI) :  0.9000
             k(s)             :                2.0000
             k(p)             :                2.4868
             k(d)             :                2.2700
             k(f)             :                0.6000
             kEN (H0ij)       :               -0.2000
             D3 a1            :                0.8000
             D3 a2            :                4.6000
             D3 s6            :                1.0000
             D3 s8            :                2.8500
             D3 s9            :                0.0000
             alphaj           :                1.1241
             ken⁴             :                4.0000
             rep dEN          :               -0.0900
             k(dz)            :                0.0000
             SRB shift        :                0.0537
             SRB prefact.     :               -0.0129
             SRB slope        :                3.4847

  Z AO/shell   Hii/eV     exponent
  1     Fri Nov 30 20:58:37 CET 2018    EN: 1.920 GAM:-0.302  GM3: 0.2474
     1s    -11.922364    1.220917
     2s     -2.806109    2.016598
  6     Fri Nov 30 20:58:37 CET 2018    EN: 2.480 GAM: 0.031  GM3: 0.0909
     2s    -15.754585    1.991584
     2p     -9.797536    1.784535
  8     Fri Nov 30 20:58:37 CET 2018    EN: 3.440 GAM: 0.058  GM3:-0.0505
     2s    -17.933232    2.671825
     2p    -11.840036    2.223991
 15     Mon Dec  3 12:53:27 CET 2018    EN: 2.190 GAM: 0.212  GM3:-0.4637
     3s    -15.707111    1.825351
     3p     -9.872569    1.785759
     3d     -1.627080    1.666137
 46     Mon Dec  3 20:24:37 CET 2018    EN: 2.200 GAM: 0.118  GM3: 0.4874
     4d    -11.047751    2.365540
     5s     -7.524596    2.046573
     5p     -1.345885    1.737074

           -------------------------------------------------
          |        Valence Tight Binding Calculation        |
           -------------------------------------------------

          ...................................................
          :                      SETUP                      :
          :.................................................:
          :  # basis functions                3874          :
          :  # atomic orbitals                3872          :
          :  # shells                         2786          :
          :  # electrons                      3220          :
          :  electronic temp.          300.0000000     K    :
          :  accuracy                    1.0000000          :
          :  -> integral cutoff          0.2500000E+02      :
          :  -> integral neglect         0.1000000E-07      :
          ...................................................
Segmentation fault: 11
```

I don't know why it's complaining about OMP_THREADS, but the more serious issue is that it's segfaulting out.  Any ideas?

I'm attaching the xyz file here as well.

Thanks,
-Eugene

**Comment by ekwan** [comment] 2020-05-10 19:54
The xyz file.

[solvated-brettphos-pd.xyz.txt](https://github.com/grimme-lab/xtb/files/4606655/solvated-brettphos-pd.xyz.txt)

**Comment by awvwgk** [comment] 2020-05-10 22:43
This probably due to insufficient `OMP_STACKSIZE`, a stackoverflow in an omp instruction usually leads to an unintelligible segmentation fault like you observed. This problem has been around for a while and there seems to be just no way to fix it from within a running `xtb` instance, we can't even check what the current stacklimit is. Increasing the stacksize and/or decreasing the number of threads might work here, depending on the avaible system resources.

For the erroneous warning I have to check the CLI which is issuing this when it thinks the the `OMP_NUM_THREADS` and the parallel option might be inconsistent.

But this seems to be an interesting edge case where the GFN0-xTB is consuming more memory then GFN2-xTB. Since you system is containing a lot of hydrogen, I would assume the memory requirement for the GFN0-xTB to be larger than for GFN2-xTB, due to the bigger basis set on hydrogen atoms, for GFN0-xTB and GFN1-xTB.

Note that we are planning to remodel the GFN0-xTB entirely.

**Comment by ekwan** [comment] 2020-05-11 02:23
Thanks for this.  I tried running the command with OMP with more memory and it gave the same result.  Running in single-threaded mode with an unlimited stack size also doesn't work.  Can we verify this problem is actually due to a memory overflow?

**Comment by awvwgk** [comment] 2020-07-13 16:44
Could be a similar issue as in #303, where `ulimit -s unlimited` was the solution.

I think this might lead to a more OSX specific issue where one cannot actually use `ulimit -s unlimited` because OSX only allows to decrease the stacksize.

**Comment by awvwgk** [comment] 2020-08-05 18:30
Closing this as duplicate of #303

**Closed by awvwgk** 2020-08-05 18:30 UTC
Labels: bug, duplicate
