### ISSUE TITLE
Crash for hessian calculations with solvation

### ISSUE THREAD

**Issue by RaphaelRobidas** [grimme-lab/xtb#289] opened 2020-06-28 15:23 UTC
**Describe the bug**
The software crashes when trying to calculate the frequency modes with solvation. As far as I can tell, the bug is independent of the structure and the solvent used.

**To Reproduce**
Run a hessian calculation with solvation, for example `xtb structure.xyz --hess -g thf` or `xtb structure.xyz --ohess -g thf`

(xtb version 6.3.1-r1 (acf1ac7) compiled by 'ehlert@majestix' on 2020-06-15)

structure.xyz:
> 4
> Title
> N          0.41850       -1.05150        0.00000
> H          0.75180       -1.99430        0.00000
> H          0.75180       -0.58010        0.81650
> H          0.75180       -0.58010       -0.81650

Output (with ohess):
> [...]
>            ------------------------------------------------- 
>           |                Numerical Hessian                |
>            ------------------------------------------------- 
> step length          :   0.00500
> SCC accuracy         :   0.30000
> Hessian scale factor :   1.00000
> frozen atoms in %    :   0.00000    0
> RMS gradient         :   0.00012
> forrtl: severe (174): SIGSEGV, segmentation fault occurred
> forrtl: severe (174): SIGSEGV, segmentation fault occurred
> forrtl: severe (153): allocatable array or pointer is not allocated
> forrtl: severe (151): allocatable array is already allocated
> forrtl: severe (151): allocatable array is already allocated
> forrtl: severe (153): allocatable array or pointer is not allocated
> 
> Stack trace terminated abnormally.

**Expected behaviour**
The hessian calculation should  be successful (as it is without solvation).

**Comment by awvwgk** [comment] 2020-06-28 17:31
Duplicate of #271, fixed with db14a9e767797c87162fb6ecc71f96d27f54c879 in #261

**Closed** 2020-06-28 17:31 UTC
Labels: bug, duplicate
